### ISSUE TITLE
How does this overlap with dxc also beeing added to llvm

### ISSUE THREAD

**Issue by fknfilewalker** [KhronosGroup/LLVM-SPIRV-Backend#206]
Since there are plans to add dxc with dxil and spirv as targets to llvm, what does this mean for this project?
[See the discourse](https://discourse.llvm.org/t/rfc-adding-hlsl-and-directx-support-to-clang-llvm/60783)

**Comment by zuban32** [comment]
It's a pretty parallel story to DXIL backend, while there still might be some common problems (e.g. opaque pointers). The code of SPIR-V target in LLVM is being taken for the upstreaming (and adapted) from this repo (for now) and the upstreaming is made by the same people who're working on this. So this is just more developed and thus unstable version of LLVM target.
