### ISSUE TITLE
Converting registers to `s32` for `ASSIGN_TYPE` interferes with instruction legality 

### ISSUE THREAD

**Issue by zainja** [KhronosGroup/LLVM-SPIRV-Backend#3]
In the instruction selector pass, there is a loop to ensure all the virtual registers for `AssignType` are mapped to `LLT::scalar(32)` 

in `SPIRVTargetMachine.cpp` 
```cpp
  for (auto &MBB : MF) {
      for (auto &MI : MBB) {
        if (MI.getOpcode() == SPIRV::ASSIGN_TYPE) {
          auto &SrcOp = MI.getOperand(1);
          if (isTypeFoldingSupported(MRI.getVRegDef(SrcOp.getReg())->getOpcode()))
            MRI.setType(MI.getOperand(0).getReg(), LLT::scalar(32));
        }
      }
    }
 ```

The problem with this is that legal instructions become illegal after it. 
## Example
consider `G_BITCAST`

`%363:id(<8 x s16>) = G_BITCAST %151:anyid(<4 x s32>)` is legal according to `SPIRVLegalizerInfo`. After the mentioned loop all  `ASSIGN_TYPE` first operands are mapped  to `s32`. This instruction becomes 
` %363:id(<8 x s16>) = G_BITCAST %151:anyid(s32)`
which is illegal because `getSizeInBits` for target and source are not equal

## Current  solution 
What I have been doing is to relax the legalizer to ensure just the target confirms with SPIRV documentation. This is not an optimal way to deal with the problem and it feels more like a hack than an actual fix.

--- 
Would it possible to make tablegen not require `s32 LLT`? or can we use SPIRV types instead of LLVM types in  `SPIRVLegalizerInfo`

**Comment by zainja** [comment]
@michalpaszkowski

**Comment by iliya-diyachkov** [comment]
This issue is probably fixed. @zainja do you have a specific test (that previously failed) to verify this?

**Comment by iliya-diyachkov** [comment]
Please reopen if the issue exists.
