### ISSUE TITLE
OpVectorExtractDynamic usage instead of OpCompositeExtract 

### ISSUE THREAD

**Issue by iliya-diyachkov** [KhronosGroup/LLVM-SPIRV-Backend#53]
OpVectorExtractDynamic usage instead of OpCompositeExtract breaks transcoding/sub_group_ballot.ll test after adding all missed builtins. For instance we get:
```
        %5 = OpTypeInt 32 0
...
        %53 = OpConstant %5 0
...
        %136 = OpGroupNonUniformBroadcast %6 %54 %135 %53
        %137 = OpVectorExtractDynamic %4 %136 %53
        %138 = OpGroupNonUniformBroadcastFirst %4 %54 %137
        OpReturn
```
but the following code is expected:
```
        %136 = OpGroupNonUniformBroadcast %6 %54 %135 %53
        %137 = OpCompositeExtract %4 %136 0
        %138 = OpGroupNonUniformBroadcastFirst %4 %54 %137
        OpReturn
```

**Comment by zuban32** [comment]
Pls check if this issue stays after my irtranslator-related changes. It might have been due to the ASSIGN_TYPE in between the G_EXTRACT_VALUE and G_CONSTANT as an index

**Comment by iliya-diyachkov** [comment]
After #52  and #72 the test is compiled with correct OpCompositeExtract instruction.
