### ISSUE TITLE
Generic issues

### ISSUE THREAD

**Issue by iliya-diyachkov** [KhronosGroup/LLVM-SPIRV-Backend#91]
This is a list of tasks that it would be nice to complete before the corresponding parts of our codebase go to LLVM repository: 
1. Remove unnecessary files, classes, definitions, includes, variables, comments...
2. Correct coding style where necessary.
I run clang-format and capitalize names of variables, maybe additional things are required.
3. Move files/code to more appropriate places, give more suitable names for some files/classes/functions.
SPIRVInstPrinter* was moved to MCTargetDesc. I'm going to rename SPIRVStrings* to SPIRVUtils* (and move some more utility code to it) and SPIRVTypeRegistry* to SPIRVGlobalRegistry* so the last one will officially support Types, Constants and Global Variables.
4. If possible, get rid of exotic solutions in the implementation.
We removed abnormal changes in target-independent part. However there are some weird things inside SPIRV-specific code. Currently I suppose we should avoid implementing these classes: SPIRVIRTranslator and SPIRVInstructionSelect. The functionality of the first one may be moved to a separate pass between IRTranslator and Legalizer (e.g. in addPreLegalizeMachineIR). The second one probably can be avoided by simplifying RegisterBanks.

**Comment by zuban32** [comment]
Just a 2 cents on '4' regarding SPIRVInstructionSelect: it's not about RegBanks, rather RegClasses mostly, and we should be able to get rid of all these weird ones (fID, vID, etc) but that would most likely mean existing tblgen patterns would be broken and we'll have to remove them and the related part in the Legalizer as well.

**Comment by iliya-diyachkov** [comment]
Thanks for the reply! I suppose RegBanks and RegClasses may be connected here. The main non-standard issue relates to disabling RegBankSelect pass and then resetting MachineFunctionProperties::Property::RegBankSelected of InstructionSelect. Two loops in SPIRVInstructionSelect::runOnMachineFunction look not to be a real problem and probably may be done before and after the pass.

**Comment by iliya-diyachkov** [comment]
The following duplication is bad too:
CMakeLists.txt 
```
add_llvm_target(SPIRVCodeGen
...
  SPIRVEnums.cpp
...
  SPIRVExtInsts.cpp
```
MCTargetDesc/CMakeLists.txt
```
add_llvm_component_library(LLVMSPIRVDesc
...
  ../SPIRVEnums.cpp
  ../SPIRVExtInsts.cpp
```
Perhaps we need to move this code to separate lib e.g. LLVMSPIRVUtils and link it to SPIRVCodeGen and LLVMSPIRVDesc like it's done in ARM, AArch64, AMDGPU and WebAssembly.

Also, we'd better increase the use of tablegen in it.
